"""Validate Construction 5's INSTRUMENT on data with known ground truth.

WHAT THIS ESTABLISHES, AND WHAT IT DOES NOT
-------------------------------------------
It establishes that the T1 comparison can tell a cover from a partition when we
already know which generated the data. It says NOTHING about MOS's own corpus:
T1-T3 need accumulated E7 assembly records, and the engine only started
recording them today.

That ordering is deliberate. An instrument that cannot recover a known answer
could not be trusted on an unknown one, so this has to pass before any verdict
about the real corpus means anything.

    python test_cover.py
"""

from __future__ import annotations

import numpy as np

from cover import (Mixture, NoisyOr, compare_model_classes, free_energy,
                   fit_mixture, fit_noisy_or, generate_mixture, generate_noisy_or,
                   interior_optimum, membership_prior, overlap_fraction,
                   permuted_null, block_split, sweep_K)

FAILURES = []


def check(name: str, ok: bool, detail: str = "") -> None:
    if ok:
        print(f"  [ok] {name}" + (f" -- {detail}" if detail else ""))
    else:
        print(f"  [FAIL] {name}" + (f" -- {detail}" if detail else ""))
        FAILURES.append(name)


# ---------------------------------------------------------------------------

def test_fitting_recovers_a_known_noisy_or():
    """EM must recover the generating model's structure, not merely converge."""
    X, truth = generate_noisy_or(N=24, K=3, T=1500, seed=1)
    fit = fit_noisy_or(X, K=3, seed=0)

    # Compare on likelihood rather than on parameters: the labels are permutable,
    # so a parameter-wise comparison would need a matching step that could hide a
    # bad fit behind a good permutation.
    ll_fit = fit.loglik(X) / X.shape[0]
    ll_truth = truth.loglik(X) / X.shape[0]
    check("EM recovers a known noisy-OR",
          ll_fit > ll_truth - 0.15,
          f"fit {ll_fit:.3f} vs truth {ll_truth:.3f} nats/tick")


def test_T1_identifies_a_cover():
    """THE instrument test, direction 1: data generated by superposing causes."""
    X, _ = generate_noisy_or(N=24, K=3, T=1200, seed=2)
    cmp = compare_model_classes(X, K=3, n_folds=4, seed=0)
    check("T1 calls cover-generated data a COVER",
          cmp.favours_cover,
          cmp.verdict())


def test_T1_identifies_a_partition():
    """Direction 2, and the one that matters more: if T1 said COVER whatever the
    data, it would be a rubber stamp and Construction 5 would be unfalsifiable."""
    X, _ = generate_mixture(N=24, K=3, T=1200, seed=3)
    cmp = compare_model_classes(X, K=3, n_folds=4, seed=0)
    check("T1 calls partition-generated data a PARTITION",
          not cmp.favours_cover,
          cmp.verdict())


def test_T2_finds_a_planted_organ_count():
    """F(K) must dip at the true K when one exists."""
    X, _ = generate_noisy_or(N=24, K=3, T=1200, seed=4)
    curve = sweep_K(X, [1, 2, 3, 4, 5, 6], seed=0)
    best = min(curve, key=lambda k: curve[k])
    check("T2 free energy dips at the planted K",
          best == 3,
          "argmin K=" + str(best) + " (planted 3); F=" +
          ", ".join(f"{k}:{curve[k]:.0f}" for k in sorted(curve)))
    check("T2 optimum is INTERIOR, not an endpoint",
          interior_optimum(curve) == 3,
          f"interior_optimum={interior_optimum(curve)}")


def test_T2_is_non_monotone_unlike_sigma_dir():
    """The point of using F(K): unlike sigma_dir under k-means, it is NOT driven
    monotonically downward by construction, so a flat curve would be a finding."""
    X, _ = generate_noisy_or(N=24, K=3, T=1200, seed=5)
    curve = sweep_K(X, [1, 2, 3, 4, 5, 6], seed=0)
    Ks = sorted(curve)
    vals = [curve[k] for k in Ks]
    monotone = all(vals[i] >= vals[i + 1] for i in range(len(vals) - 1))
    check("T2 curve is not monotone decreasing",
          not monotone,
          "so an absent optimum would be a FINDING, not an artefact")


def test_T3_detects_real_overlap_and_its_absence():
    """Overlap must be measured, not assumed. Cover-generated data has it;
    partition-generated data must NOT show it (failure mode 3)."""
    Xc, _ = generate_noisy_or(N=24, K=3, T=1200, seed=6, overlap=0.4)
    fit_c = fit_noisy_or(Xc, K=3, seed=0)
    frac_c = overlap_fraction(fit_c)

    Xp, _ = generate_mixture(N=24, K=3, T=1200, seed=7)
    fit_p = fit_noisy_or(Xp, K=3, seed=0)
    frac_p = overlap_fraction(fit_p)

    check("T3 finds overlap in cover-generated data", frac_c > 0.05,
          f"{frac_c:.3f} of concepts claimed by >1 organ")
    check("T3 finds LESS overlap in partition-generated data", frac_p < frac_c,
          f"partition {frac_p:.3f} < cover {frac_c:.3f}")


def test_T4_null_destroys_the_structure():
    """The structureless null must not retain an organ count. If it did, T2's
    optimum would be an artefact of the instrument rather than a fact about the
    corpus -- which is exactly the defect 5ak's k-sweep had."""
    X, _ = generate_noisy_or(N=24, K=3, T=1200, seed=8)
    Y = permuted_null(X, seed=0)

    check("null preserves assembly sizes",
          np.array_equal(X.sum(axis=1), Y.sum(axis=1)),
          "sizes identical, co-activation destroyed")

    real = sweep_K(X, [1, 2, 3, 4, 5], seed=0)
    null = sweep_K(Y, [1, 2, 3, 4, 5], seed=0)
    real_gain = real[1] - min(real.values())
    null_gain = null[1] - min(null.values())
    check("real data gains far more from extra organs than the null does",
          real_gain > 3 * max(null_gain, 1e-9),
          f"real gain {real_gain:.0f} vs null gain {null_gain:.0f} nats")


def test_block_split_is_contiguous():
    """Random tick splits would leak: assemblies are temporally correlated, so a
    held-out tick between two training ticks is nearly determined by them."""
    folds = block_split(100, n_folds=5)
    ok = all(np.array_equal(test, np.arange(test[0], test[-1] + 1)) for _, test in folds)
    disjoint = all(len(np.intersect1d(tr, te)) == 0 for tr, te in folds)
    check("held-out folds are contiguous blocks and disjoint from train",
          ok and disjoint, f"{len(folds)} folds")


def test_membership_prior_is_beta_not_dirichlet():
    """At n=0 the prior returns the hand-set list; and crucially sum_i theta_ci
    is NOT forced to 1, or the partition would be smuggled back in through the
    prior even under a noisy-OR likelihood."""
    N, K = 6, 3
    pi0 = np.zeros((N, K))
    pi0[0:2, 0] = 1.0
    pi0[2:4, 1] = 1.0
    pi0[4:6, 2] = 1.0
    # Concept 0 is claimed by TWO hand-set modules -- overlap in the prior itself.
    pi0[0, 1] = 1.0

    n_ci = np.zeros((N, K))
    m_i = np.zeros(K)
    theta0 = membership_prior(n_ci, m_i, pi0, kappa=5.0)

    check("at n=0 the prior reproduces the hand-set list",
          np.allclose(theta0, np.clip(pi0, 1e-6, 1 - 1e-6), atol=1e-6),
          "kappa observations' worth of hand-set structure")
    check("sum_i theta_ci may EXCEED 1 (Beta-per-pair, not Dirichlet)",
          theta0[0].sum() > 1.5,
          f"concept 0 sums to {theta0[0].sum():.3f} -- overlap survives the prior")

    # As evidence accumulates, the data wins.
    n_ci = np.zeros((N, K))
    n_ci[0, 2] = 500.0
    m_i = np.array([10.0, 10.0, 500.0])
    theta1 = membership_prior(n_ci, m_i, pi0, kappa=5.0)
    check("evidence moves the prior toward the data",
          theta1[0, 2] > 0.9,
          f"theta[0,2] = {theta1[0,2]:.3f} after 500 co-activations")


def test_refusals():
    ok = True
    try:
        membership_prior(np.zeros((2, 2)), np.zeros(2), np.zeros((2, 3)), 1.0)
        ok = False
    except ValueError:
        pass
    try:
        membership_prior(np.zeros((2, 2)), np.zeros(2), np.zeros((2, 2)), 0.0)
        ok = False
    except ValueError:
        pass
    try:
        from cover import _configs
        _configs(50)
        ok = False
    except ValueError:
        pass
    check("shape mismatch, kappa<=0 and an absurd K are all refused", ok)


def main() -> int:
    print("=== Construction 5: instrument validation on KNOWN ground truth ===")
    test_fitting_recovers_a_known_noisy_or()
    print("--- T1: the model-class comparison (both directions) ---")
    test_T1_identifies_a_cover()
    test_T1_identifies_a_partition()
    print("--- T2: free energy over K ---")
    test_T2_finds_a_planted_organ_count()
    test_T2_is_non_monotone_unlike_sigma_dir()
    print("--- T3 / T4: overlap and the structureless null ---")
    test_T3_detects_real_overlap_and_its_absence()
    test_T4_null_destroys_the_structure()
    print("--- machinery ---")
    test_block_split_is_contiguous()
    test_membership_prior_is_beta_not_dirichlet()
    test_refusals()

    print()
    if FAILURES:
        print(f"{len(FAILURES)} FAILURE(S): " + ", ".join(FAILURES))
        return 1
    print("INSTRUMENT VALIDATED ON SYNTHETIC DATA.")
    print("It has NOT been run on MOS's corpus -- that needs accumulated E7 records.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
