# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConstraintPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConstraintPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConstraintPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConstraintPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConstraintPayload
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ConstraintPayload
    def Geometry(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ConstraintPayload
    def GeometryAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ConstraintPayload
    def GeometryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ConstraintPayload
    def GeometryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ConstraintPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    ConstraintPayloadStart(builder)

def ConstraintPayloadAddType(builder, type):
    builder.PrependInt8Slot(0, type, 0)

def AddType(builder, type):
    ConstraintPayloadAddType(builder, type)

def ConstraintPayloadAddGeometry(builder, geometry):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(geometry), 0)

def AddGeometry(builder, geometry):
    ConstraintPayloadAddGeometry(builder, geometry)

def ConstraintPayloadStartGeometryVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGeometryVector(builder, numElems: int) -> int:
    return ConstraintPayloadStartGeometryVector(builder, numElems)

def ConstraintPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConstraintPayloadEnd(builder)
