# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OperadDAG(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OperadDAG()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOperadDAG(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OperadDAG
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OperadDAG
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mos.fbs.OperadNode import OperadNode
            obj = OperadNode()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OperadDAG
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OperadDAG
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OperadDAGStart(builder):
    builder.StartObject(1)

def Start(builder):
    OperadDAGStart(builder)

def OperadDAGAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    OperadDAGAddNodes(builder, nodes)

def OperadDAGStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems: int) -> int:
    return OperadDAGStartNodesVector(builder, numElems)

def OperadDAGEnd(builder):
    return builder.EndObject()

def End(builder):
    return OperadDAGEnd(builder)
