# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OperadNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OperadNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOperadNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OperadNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OperadNode
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OperadNode
    def Operator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mos.fbs.Operator import Operator
            obj = Operator()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OperadNode
    def ChildrenIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OperadNode
    def ChildrenIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OperadNode
    def ChildrenIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OperadNode
    def ChildrenIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def OperadNodeStart(builder):
    builder.StartObject(3)

def Start(builder):
    OperadNodeStart(builder)

def OperadNodeAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    OperadNodeAddId(builder, id)

def OperadNodeAddOperator(builder, operator):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(operator), 0)

def AddOperator(builder, operator):
    OperadNodeAddOperator(builder, operator)

def OperadNodeAddChildrenIds(builder, childrenIds):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(childrenIds), 0)

def AddChildrenIds(builder, childrenIds):
    OperadNodeAddChildrenIds(builder, childrenIds)

def OperadNodeStartChildrenIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChildrenIdsVector(builder, numElems: int) -> int:
    return OperadNodeStartChildrenIdsVector(builder, numElems)

def OperadNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return OperadNodeEnd(builder)
