# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class OpType(object):
    UNKNOWN = 0
    SEARCH = 1
    COMPUTE = 2
    REASON = 3
    RESPOND = 4
    CONTEXT = 5
    VERIFY = 6
