// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OPERAD_MOS_FBS_H_
#define FLATBUFFERS_GENERATED_OPERAD_MOS_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace mos {
namespace fbs {

struct ConstraintPayload;
struct ConstraintPayloadBuilder;

struct Operator;
struct OperatorBuilder;

struct OperadNode;
struct OperadNodeBuilder;

struct OperadDAG;
struct OperadDAGBuilder;

enum OpType : int8_t {
  OpType_UNKNOWN = 0,
  OpType_SEARCH = 1,
  OpType_COMPUTE = 2,
  OpType_REASON = 3,
  OpType_RESPOND = 4,
  OpType_CONTEXT = 5,
  OpType_VERIFY = 6,
  OpType_MIN = OpType_UNKNOWN,
  OpType_MAX = OpType_VERIFY
};

inline const OpType (&EnumValuesOpType())[7] {
  static const OpType values[] = {
    OpType_UNKNOWN,
    OpType_SEARCH,
    OpType_COMPUTE,
    OpType_REASON,
    OpType_RESPOND,
    OpType_CONTEXT,
    OpType_VERIFY
  };
  return values;
}

inline const char * const *EnumNamesOpType() {
  static const char * const names[8] = {
    "UNKNOWN",
    "SEARCH",
    "COMPUTE",
    "REASON",
    "RESPOND",
    "CONTEXT",
    "VERIFY",
    nullptr
  };
  return names;
}

inline const char *EnumNameOpType(OpType e) {
  if (::flatbuffers::IsOutRange(e, OpType_UNKNOWN, OpType_VERIFY)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOpType()[index];
}

enum ConstraintType : int8_t {
  ConstraintType_RIGID = 0,
  ConstraintType_FLUID = 1,
  ConstraintType_MIN = ConstraintType_RIGID,
  ConstraintType_MAX = ConstraintType_FLUID
};

inline const ConstraintType (&EnumValuesConstraintType())[2] {
  static const ConstraintType values[] = {
    ConstraintType_RIGID,
    ConstraintType_FLUID
  };
  return values;
}

inline const char * const *EnumNamesConstraintType() {
  static const char * const names[3] = {
    "RIGID",
    "FLUID",
    nullptr
  };
  return names;
}

inline const char *EnumNameConstraintType(ConstraintType e) {
  if (::flatbuffers::IsOutRange(e, ConstraintType_RIGID, ConstraintType_FLUID)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesConstraintType()[index];
}

struct ConstraintPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConstraintPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_GEOMETRY = 6
  };
  mos::fbs::ConstraintType type() const {
    return static_cast<mos::fbs::ConstraintType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<float> *geometry() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_GEOMETRY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_GEOMETRY) &&
           verifier.VerifyVector(geometry()) &&
           verifier.EndTable();
  }
};

struct ConstraintPayloadBuilder {
  typedef ConstraintPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(mos::fbs::ConstraintType type) {
    fbb_.AddElement<int8_t>(ConstraintPayload::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_geometry(::flatbuffers::Offset<::flatbuffers::Vector<float>> geometry) {
    fbb_.AddOffset(ConstraintPayload::VT_GEOMETRY, geometry);
  }
  explicit ConstraintPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConstraintPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConstraintPayload>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConstraintPayload> CreateConstraintPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    mos::fbs::ConstraintType type = mos::fbs::ConstraintType_RIGID,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> geometry = 0) {
  ConstraintPayloadBuilder builder_(_fbb);
  builder_.add_geometry(geometry);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConstraintPayload> CreateConstraintPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    mos::fbs::ConstraintType type = mos::fbs::ConstraintType_RIGID,
    const std::vector<float> *geometry = nullptr) {
  auto geometry__ = geometry ? _fbb.CreateVector<float>(*geometry) : 0;
  return mos::fbs::CreateConstraintPayload(
      _fbb,
      type,
      geometry__);
}

struct Operator FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OperatorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_PAYLOAD = 6,
    VT_SUPPORT = 8,
    VT_CONSTRAINTS = 10,
    VT_GEOMETRY = 12
  };
  mos::fbs::OpType type() const {
    return static_cast<mos::fbs::OpType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::String *payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD);
  }
  const ::flatbuffers::Vector<int32_t> *support() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_SUPPORT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::ConstraintPayload>> *constraints() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::ConstraintPayload>> *>(VT_CONSTRAINTS);
  }
  const ::flatbuffers::Vector<float> *geometry() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_GEOMETRY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           VerifyOffset(verifier, VT_SUPPORT) &&
           verifier.VerifyVector(support()) &&
           VerifyOffset(verifier, VT_CONSTRAINTS) &&
           verifier.VerifyVector(constraints()) &&
           verifier.VerifyVectorOfTables(constraints()) &&
           VerifyOffset(verifier, VT_GEOMETRY) &&
           verifier.VerifyVector(geometry()) &&
           verifier.EndTable();
  }
};

struct OperatorBuilder {
  typedef Operator Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(mos::fbs::OpType type) {
    fbb_.AddElement<int8_t>(Operator::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::String> payload) {
    fbb_.AddOffset(Operator::VT_PAYLOAD, payload);
  }
  void add_support(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> support) {
    fbb_.AddOffset(Operator::VT_SUPPORT, support);
  }
  void add_constraints(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::ConstraintPayload>>> constraints) {
    fbb_.AddOffset(Operator::VT_CONSTRAINTS, constraints);
  }
  void add_geometry(::flatbuffers::Offset<::flatbuffers::Vector<float>> geometry) {
    fbb_.AddOffset(Operator::VT_GEOMETRY, geometry);
  }
  explicit OperatorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Operator> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Operator>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Operator> CreateOperator(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    mos::fbs::OpType type = mos::fbs::OpType_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::String> payload = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> support = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::ConstraintPayload>>> constraints = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> geometry = 0) {
  OperatorBuilder builder_(_fbb);
  builder_.add_geometry(geometry);
  builder_.add_constraints(constraints);
  builder_.add_support(support);
  builder_.add_payload(payload);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Operator> CreateOperatorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    mos::fbs::OpType type = mos::fbs::OpType_UNKNOWN,
    const char *payload = nullptr,
    const std::vector<int32_t> *support = nullptr,
    const std::vector<::flatbuffers::Offset<mos::fbs::ConstraintPayload>> *constraints = nullptr,
    const std::vector<float> *geometry = nullptr) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  auto support__ = support ? _fbb.CreateVector<int32_t>(*support) : 0;
  auto constraints__ = constraints ? _fbb.CreateVector<::flatbuffers::Offset<mos::fbs::ConstraintPayload>>(*constraints) : 0;
  auto geometry__ = geometry ? _fbb.CreateVector<float>(*geometry) : 0;
  return mos::fbs::CreateOperator(
      _fbb,
      type,
      payload__,
      support__,
      constraints__,
      geometry__);
}

struct OperadNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OperadNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_OPERATOR_ = 6,
    VT_CHILDREN_IDS = 8
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const mos::fbs::Operator *operator_() const {
    return GetPointer<const mos::fbs::Operator *>(VT_OPERATOR_);
  }
  const ::flatbuffers::Vector<int32_t> *children_ids() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_CHILDREN_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_OPERATOR_) &&
           verifier.VerifyTable(operator_()) &&
           VerifyOffset(verifier, VT_CHILDREN_IDS) &&
           verifier.VerifyVector(children_ids()) &&
           verifier.EndTable();
  }
};

struct OperadNodeBuilder {
  typedef OperadNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(OperadNode::VT_ID, id, 0);
  }
  void add_operator_(::flatbuffers::Offset<mos::fbs::Operator> operator_) {
    fbb_.AddOffset(OperadNode::VT_OPERATOR_, operator_);
  }
  void add_children_ids(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> children_ids) {
    fbb_.AddOffset(OperadNode::VT_CHILDREN_IDS, children_ids);
  }
  explicit OperadNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OperadNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OperadNode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OperadNode> CreateOperadNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<mos::fbs::Operator> operator_ = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> children_ids = 0) {
  OperadNodeBuilder builder_(_fbb);
  builder_.add_children_ids(children_ids);
  builder_.add_operator_(operator_);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OperadNode> CreateOperadNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<mos::fbs::Operator> operator_ = 0,
    const std::vector<int32_t> *children_ids = nullptr) {
  auto children_ids__ = children_ids ? _fbb.CreateVector<int32_t>(*children_ids) : 0;
  return mos::fbs::CreateOperadNode(
      _fbb,
      id,
      operator_,
      children_ids__);
}

struct OperadDAG FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OperadDAGBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::OperadNode>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::OperadNode>> *>(VT_NODES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           verifier.EndTable();
  }
};

struct OperadDAGBuilder {
  typedef OperadDAG Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::OperadNode>>> nodes) {
    fbb_.AddOffset(OperadDAG::VT_NODES, nodes);
  }
  explicit OperadDAGBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OperadDAG> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OperadDAG>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OperadDAG> CreateOperadDAG(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mos::fbs::OperadNode>>> nodes = 0) {
  OperadDAGBuilder builder_(_fbb);
  builder_.add_nodes(nodes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OperadDAG> CreateOperadDAGDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<mos::fbs::OperadNode>> *nodes = nullptr) {
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<mos::fbs::OperadNode>>(*nodes) : 0;
  return mos::fbs::CreateOperadDAG(
      _fbb,
      nodes__);
}

inline const mos::fbs::OperadDAG *GetOperadDAG(const void *buf) {
  return ::flatbuffers::GetRoot<mos::fbs::OperadDAG>(buf);
}

inline const mos::fbs::OperadDAG *GetSizePrefixedOperadDAG(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<mos::fbs::OperadDAG>(buf);
}

inline bool VerifyOperadDAGBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<mos::fbs::OperadDAG>(nullptr);
}

inline bool VerifySizePrefixedOperadDAGBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<mos::fbs::OperadDAG>(nullptr);
}

inline void FinishOperadDAGBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mos::fbs::OperadDAG> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOperadDAGBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<mos::fbs::OperadDAG> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs
}  // namespace mos

#endif  // FLATBUFFERS_GENERATED_OPERAD_MOS_FBS_H_
