"""Construction 5, Tier 0, against an accumulated E7 log.

TIERS ARE GATES. T1 first: if the cover loses, Constructions 4 AND 5 are refuted
and T2/T3 are not worth running. That ordering is enforced here rather than left
to the reader.

    T1  noisy-OR vs mixture on held-out predictive log-likelihood
    T2  F(K) interior optimum over a bounded K sweep
    T3  overlap is real -- fraction of concepts claimed by more than one organ

USES calibrated_compare, NOT compare_model_classes. The latter's pass criterion
is `margin > 0`, which on data generated by a weak PARTITION returns COVER at
rates up to 1.00 -- it measures the noisy-OR's extra latent flexibility (2^K
configurations against the mixture's K at the same parameter count), not the
latent structure. Anything reported from the uncalibrated rule is an artefact.

READS `retrieved`, NEVER `grown`. Retrieval is the co-activation event: one
Wasserstein query returns a SET, and sets overlap across ticks. Neurogenesis
grows each concept exactly once, so a matrix built from `grown` has a single
firing per column and measures growth order.

    python run_tier0.py --log assembly_events.jsonl
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from typing import Dict, List

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from assembly_log import DEFAULT_PATH                       # noqa: E402
from cover import (assemblies_to_matrix, calibrated_compare, sweep_K,  # noqa: E402
                   interior_optimum, overlap_fraction, fit_noisy_or,
                   permuted_null, MAX_K)


def load_assemblies(path: str):
    """Every closed tick's retrieved set, plus the birth register."""
    rows, births = [], {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            rows.append(list(ev.get("retrieved") or []))
            for g in (ev.get("grown") or []):
                births.setdefault(g, len(rows) - 1)
    return rows, births


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--log", default=DEFAULT_PATH)
    ap.add_argument("--K", type=int, default=6, help="organ count for T1/T3")
    ap.add_argument("--B", type=int, default=39, help="bootstrap draws for T1")
    ap.add_argument("--alpha", type=float, default=0.05)
    ap.add_argument("--min-concepts", type=int, default=2,
                    help="drop concepts seen in fewer ticks than this")
    args = ap.parse_args()

    if not os.path.exists(args.log):
        print(f"[tier0] no log at {args.log}", file=sys.stderr)
        return 2

    rows, births = load_assemblies(args.log)
    T_all = len(rows)
    sizes = np.array([len(r) for r in rows]) if rows else np.array([0])

    print(f"[tier0] ticks in log        : {T_all}")
    print(f"[tier0] mean assembly size  : {sizes.mean():.2f} "
          f"(median {np.median(sizes):.0f}, max {sizes.max()})")
    print(f"[tier0] ticks with >=2      : {int((sizes >= 2).sum())} "
          f"({100.0*(sizes >= 2).mean():.1f}%)")

    if (sizes >= 2).sum() < 50:
        # A co-activation model needs co-activations. Saying so is the finding;
        # fitting anyway would produce a verdict about ~nothing.
        print("\n[tier0] STOP: fewer than 50 ticks retrieved 2+ concepts, so there "
              "is essentially no co-activation to explain. A cover/partition "
              "verdict from this log would be meaningless. Widen retrieval or "
              "enlarge the corpus before rerunning.", file=sys.stderr)
        return 3

    counts = Counter(c for r in rows for c in r)
    keep = sorted(c for c, n in counts.items() if n >= args.min_concepts)
    index: Dict[str, int] = {c: i for i, c in enumerate(keep)}
    N = len(keep)
    print(f"[tier0] concepts (>= {args.min_concepts} ticks): {N} "
          f"of {len(counts)} seen")

    if N < 2 * args.K:
        print(f"[tier0] STOP: {N} concepts is too few for K={args.K} organs.",
              file=sys.stderr)
        return 3

    idx_rows: List[List[int]] = [[index[c] for c in r if c in index] for r in rows]
    keep_t = [i for i, r in enumerate(idx_rows) if r]
    X = assemblies_to_matrix([idx_rows[i] for i in keep_t], N)
    T = X.shape[0]
    print(f"[tier0] matrix              : {T} x {N}, density {X.mean():.4f}")

    # The KB is STATIC during a SEARCH-only run -- nothing commits new concepts
    # mid-stream -- so every column existed at every tick and the alive mask is
    # all ones. Stated rather than assumed: it stops being true the moment the
    # curator writes back during accumulation, and then this must become a real
    # mask built from `births`.
    mask = None
    if births:
        print(f"[tier0] NOTE: {len(births)} concepts were GROWN during the run. "
              "Those are CognitiveState vertices, not KB concepts, so they are "
              "not columns here; the alive mask stays all-ones.")

    print("\n=== T1: is the latent structure a COVER or a PARTITION? ===")
    res = calibrated_compare(X, K=args.K, B=args.B, seed=0, alpha=args.alpha, mask=mask)
    print(f"  observed margin   : {res.observed:+.4f} nats/tick")
    print(f"  fitted-partition  : median {np.median(res.null):+.4f}, "
          f"[{res.null.min():+.4f}, {res.null.max():+.4f}] over {len(res.null)} draws")
    print(f"  excess over null  : {res.excess_over_null:+.4f}  <- the honest effect size")
    print(f"  p                 : {res.p_value:.4f}")
    print(f"  VERDICT: {res.verdict()}")

    if not res.favours_cover:
        print("\n[tier0] T1 did not find evidence for a cover. Per the tiering, "
              "T2/T3 are not run: they describe a cover's shape, and there is no "
              "established cover to describe.")
        print("[tier0] NOTE: this is NOT a positive finding for the partition. "
              "At weak effect sizes the calibrated test has low power (0.17 at "
              "T=700, 0.75 at T=1500, 1.00 at T=3000), so an inconclusive result "
              "at small T is expected whichever hypothesis is true.")
        return 0

    print("\n=== T2: is there a natural organ count? ===")
    Ks = [k for k in range(2, min(args.K + 5, MAX_K)) ]
    curve = sweep_K(X, Ks, seed=0)
    for k in Ks:
        print(f"  K={k:2d}  F={curve[k]:.1f}")
    best = interior_optimum(curve)
    print(f"  interior optimum: {best if best else 'NONE (endpoint) -- no natural scale'}")

    print("\n=== T3: is the overlap real? ===")
    model = fit_noisy_or(X, args.K, seed=0, mask=mask)
    frac = overlap_fraction(model)
    null_frac = overlap_fraction(fit_noisy_or(permuted_null(X, seed=0), args.K, seed=0))
    print(f"  concepts claimed by >1 organ : {frac:.3f}")
    print(f"  same on the permuted null    : {null_frac:.3f}")
    print(f"  {'overlap exceeds the structureless null' if frac > null_frac else 'NO excess over null -- overlap may be fiction'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
